/* eslint-disable */

export default {
  SAVE_USER_REQUEST: 'SAVE_USER_REQUEST',
  SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
  SAVE_USER_FAILURE: 'SAVE_USER_FAILURE',
  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILUR: 'DELETE_USER_FAILURE',
  LOGIN_USER_REQUEST: 'DELETE_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'DELETE_USER_FAILURE',
  RESET_USER_PASSWORD_REQUEST: 'RESET_USER_PASSWORD_REQUEST',
  RESET_USER_PASSWORD_SUCCESS: 'RESET_USER_PASSWORD_SUCCESS',
  RESET_USER_PASSWORD_FAILURE: 'RESET_USER_PASSWORD_FAILURE',
};
